using Dapper;

namespace SmugglerWebAdmin.Data
{
    /// <summary>
    /// 앱 시작 시 PostgreSQL에 필요한 테이블을 생성합니다.<br/>
    /// CREATE TABLE IF NOT EXISTS 방식으로 멱등 실행됩니다.
    /// </summary>
    public class SchemaInitializer
    {
        private readonly IDbConnectionFactory _connectionFactory;

        public SchemaInitializer(IDbConnectionFactory connectionFactory)
        {
            _connectionFactory = connectionFactory;
        }

        public async Task InitializeAsync()
        {
            await using var conn = _connectionFactory.CreateConnection();
            await conn.OpenAsync();

            await conn.ExecuteAsync("""
                CREATE TABLE IF NOT EXISTS "AspNetUsers" (
                    "Id"                   text        NOT NULL,
                    "UserName"             text,
                    "NormalizedUserName"   text,
                    "Email"                text,
                    "NormalizedEmail"      text,
                    "EmailConfirmed"       boolean     NOT NULL DEFAULT false,
                    "PasswordHash"         text,
                    "SecurityStamp"        text,
                    "ConcurrencyStamp"     text,
                    "PhoneNumber"          text,
                    "PhoneNumberConfirmed" boolean     NOT NULL DEFAULT false,
                    "TwoFactorEnabled"     boolean     NOT NULL DEFAULT false,
                    "LockoutEnd"           timestamp with time zone,
                    "LockoutEnabled"       boolean     NOT NULL DEFAULT false,
                    "AccessFailedCount"    integer     NOT NULL DEFAULT 0,
                    "CreatedAt"            timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_AspNetUsers_NormalizedUserName"
                    ON "AspNetUsers" ("NormalizedUserName")
                    WHERE "NormalizedUserName" IS NOT NULL;

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_AspNetUsers_NormalizedEmail"
                    ON "AspNetUsers" ("NormalizedEmail")
                    WHERE "NormalizedEmail" IS NOT NULL;

                CREATE TABLE IF NOT EXISTS "Services" (
                    "Id"          integer     GENERATED BY DEFAULT AS IDENTITY,
                    "Name"        text        NOT NULL,
                    "DisplayName" text        NOT NULL,
                    "IsActive"    boolean     NOT NULL DEFAULT true,
                    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "ServiceRegions" (
                    "Id"          integer     GENERATED BY DEFAULT AS IDENTITY,
                    "ServiceId"   integer     NOT NULL,
                    "Name"        text        NOT NULL,
                    "DisplayName" text        NOT NULL,
                    "IsActive"    boolean     NOT NULL DEFAULT true,
                    CONSTRAINT "PK_ServiceRegions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_ServiceRegions_Services" FOREIGN KEY ("ServiceId")
                        REFERENCES "Services" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_ServiceRegions_ServiceId"
                    ON "ServiceRegions" ("ServiceId");

                CREATE TABLE IF NOT EXISTS "RegionEnvironments" (
                    "Id"              integer GENERATED BY DEFAULT AS IDENTITY,
                    "ServiceRegionId" integer NOT NULL,
                    "Name"            text    NOT NULL,
                    "DisplayName"     text    NOT NULL,
                    "ToolUrl"         text    NOT NULL DEFAULT '',
                    "IsActive"        boolean NOT NULL DEFAULT true,
                    CONSTRAINT "PK_RegionEnvironments" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_RegionEnvironments_ServiceRegions" FOREIGN KEY ("ServiceRegionId")
                        REFERENCES "ServiceRegions" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_RegionEnvironments_ServiceRegionId"
                    ON "RegionEnvironments" ("ServiceRegionId");

                CREATE TABLE IF NOT EXISTS "UserServicePermissions" (
                    "Id"        integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId"    text    NOT NULL,
                    "ServiceId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "PK_UserServicePermissions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_UserServicePermissions_Users"    FOREIGN KEY ("UserId")
                        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_UserServicePermissions_Services" FOREIGN KEY ("ServiceId")
                        REFERENCES "Services" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_UserServicePermissions_UserId_ServiceId"
                    ON "UserServicePermissions" ("UserId", "ServiceId");

                CREATE TABLE IF NOT EXISTS "UserServiceRegionPermissions" (
                    "Id"              integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId"          text    NOT NULL,
                    "ServiceRegionId" integer NOT NULL,
                    "CreatedAt"       timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "PK_UserServiceRegionPermissions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_UserServiceRegionPermissions_Users"   FOREIGN KEY ("UserId")
                        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_UserServiceRegionPermissions_Regions" FOREIGN KEY ("ServiceRegionId")
                        REFERENCES "ServiceRegions" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_UserServiceRegionPermissions_UserId_ServiceRegionId"
                    ON "UserServiceRegionPermissions" ("UserId", "ServiceRegionId");

                CREATE TABLE IF NOT EXISTS "UserRegionEnvironmentPermissions" (
                    "Id"                  integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId"              text    NOT NULL,
                    "RegionEnvironmentId" integer NOT NULL,
                    "CreatedAt"           timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "PK_UserRegionEnvironmentPermissions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_UserRegionEnvironmentPermissions_Users" FOREIGN KEY ("UserId")
                        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_UserRegionEnvironmentPermissions_Envs"  FOREIGN KEY ("RegionEnvironmentId")
                        REFERENCES "RegionEnvironments" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_UserRegionEnvironmentPermissions_UserId_RegionEnvironmentId"
                    ON "UserRegionEnvironmentPermissions" ("UserId", "RegionEnvironmentId");
                """);

            // 기존 DB에 새 컬럼이 없을 경우 추가 (멱등)
            await conn.ExecuteAsync("""
                ALTER TABLE "AspNetUsers"
                    ADD COLUMN IF NOT EXISTS "IsAdmin"            boolean NOT NULL DEFAULT false,
                    ADD COLUMN IF NOT EXISTS "IsSuperAdmin"       boolean NOT NULL DEFAULT false,
                    ADD COLUMN IF NOT EXISTS "MustChangePassword" boolean NOT NULL DEFAULT false,
                    ADD COLUMN IF NOT EXISTS "IsActive"           boolean NOT NULL DEFAULT true;
                """);
        }
    }
}
